kind: BuildConfig
apiVersion: v1
metadate:
    name: script-checkout
    namespace: cicd
spec:
  source:
    git:
      uri: "git@github.com:muralidharansomasundaram/test-cicd.git"
  strategy:
    jenkinsPipelineStratagey:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: " container_name: "
          value: testcicd
        - name: " git_branch" 
          value: " master"

